version: "3"
services:
  api:
    container_name: bitu-api
    restart: unless-stopped
    build:
      context: ./bitu-api
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./bitu-api:/app
    env_file: ./bitu-api/.env
    ports:
      - "9000:9000"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    networks:
      - bitu-network

  client:
    container_name: bitu-client
    restart: unless-stopped
    build:
      context: ./bitu-client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./bitu-client:/app
    env_file: ./bitu-client/.env
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
      - api
    networks:
      - bitu-network

  db:
    image: mongo:5.0
    restart: unless-stopped
    volumes:
      - .docker/data/db:/data/db
    networks:
      - bitu-network

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    volumes:
      - .docker/data/redis:/data/redis
    networks:
      - bitu-network
networks:
  bitu-network:
    driver: bridge
